services:

  user-management:
    ports:
      - "9080:8080"
      - "9081:8081"

  media-management:
    ports:
      - "9090:8080"
      - "9091:8081"

  media-player-endpoint:
    ports:
      - "9100:8080"
      - "9101:8081"

  media-comment:
    ports:
      - "9140:8080"
      - "9141:8081"

  admin-app:
    ports:
      - "9110:8080"
      - "9111:8081"

  qa-endpoint-app:
    ports:
      - "9120:8080"
      - "9121:8081"

  media-metrics:
    ports:
      - "9130:8080"
      - "9131:8081"

  kafka-connect:
    ports:
      - "8083:8083"