services:
  mysql-loaded:
    image: eclipse-temurin:21-jre-alpine
    command: >
      sh -c "while ! nc -z mysql 3306; do 
               echo 'Waiting for MySQL...'; 
               sleep 1; 
             done; 
             echo 'MySQL is up';"

  postgres-loaded:
    image: eclipse-temurin:21-jre-alpine
    command: >
      sh -c "while ! nc -z postgres 5432; do 
               echo 'Waiting for postgres...'; 
               sleep 1; 
             done; 
             echo 'Postgres is up';"

  redis-loaded:
    image: eclipse-temurin:21-jre-alpine
    command: >
      sh -c "while ! nc -z redis 6379; do 
               echo 'Waiting for Redis...'; 
               sleep 1; 
             done; 
             echo 'Redis is up';"

  kafka-loaded:
    image: eclipse-temurin:21-jre-alpine
    command: >
      sh -c "while ! nc -z broker 9092 || ! nc -z schema-registry 8091 || ! nc -z kafka-connect 8083; do 
               echo 'Waiting for kafka, kafka-connect And Schema Registry...'; 
               sleep 1; 
             done; 
             echo 'kafka, kafka-connect And Schema Registry is up';"

  user-management:
    build:
      context: apps/user-management/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securePostgresPassword123
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 55s
      retries: 3
      start_period: 35s
    depends_on:
      postgres-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully

  media-management:
    build:
      context: apps/media-management/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      MYSQL_USER: user
      MYSQL_PASSWORD: securePassword123
      MYSQL_HOST: mysql
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securePostgresPassword123
      POSTGRES_HOST: postgres
    depends_on:
      mysql-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 35s
      retries: 3
      start_period: 35s

  media-metrics:
    build:
      context: apps/media-metric-endpoint/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securePostgresPassword123
      POSTGRES_HOST: postgres
    depends_on:
      postgres-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 35s
      retries: 3
      start_period: 35s

  media-player-endpoint:
    build:
      context: apps/media-player-endpoint/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      KAFKA_SCHEMA_REGISTRY_URL: http://schema-registry:8091
      KAFKA_BOOTSTRAP_SERVERS: broker:29092
    depends_on:
      kafka-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 35s
      retries: 3
      start_period: 35s

  media-comment:
    build:
      context: apps/media-comment/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securePostgresPassword123
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 55s
      retries: 3
      start_period: 35s
    depends_on:
      postgres-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully

  admin-app:
    build:
      context: apps/admin-endpoint/webapp
      dockerfile: ../../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      PUBLIC_REST_PORT: 8080
      REDIS_HOST: redis
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: securePostgresPassword123
      POSTGRES_HOST: postgres
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 35s
      retries: 3
      start_period: 35s
    depends_on:
      postgres-loaded:
        condition: service_completed_successfully
      mysql-loaded:
        condition: service_completed_successfully
      redis-loaded:
        condition: service_completed_successfully

  qa-endpoint-app:
    build:
      context: qa-endpoint-root/qa-endpoint-webapp
      dockerfile: ../../Dockerfile
    ports:
      - "8080"
      - "8081"
    environment:
      REDIS_HOST: redis
      PUBLIC_REST_PORT: 8080
      ADMIN_ENDOPOINT_PORT: 8080
      MEDIA_MANAGEMENT_PORT: 8080
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8081"]
      interval: 10s
      timeout: 35s
      retries: 3
      start_period: 35s
    depends_on:
      admin-app:
        condition: service_healthy
      user-management:
        condition: service_healthy
      media-management:
        condition: service_healthy
      media-player-endpoint:
        condition: service_healthy

