
CREATE SCHEMA media;

CREATE TABLE media.comment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id          UUID                                    NOT NULL,
    user_id            UUID                                    NOT NULL,
    record_type        VARCHAR(255)                            NOT NULL,
    record_id          UUID                                    NOT NULL,
    comment            VARCHAR(1025)                           NOT NULL,
    media_position_ms  BIGINT,
    creation_timestamp TIMESTAMP WITHOUT TIME ZONE,
    last_updated_date  TIMESTAMP WITHOUT TIME ZONE,
    deletion_timestamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comment PRIMARY KEY (id)
);

ALTER TABLE media.comment
    ADD CONSTRAINT uc_comment_public UNIQUE (public_id);
