spring.profiles.include=core,postgres,redis,security

spring.application.name=MediaComments

spring.datasource.postgresql.schema=${POSTGRES_SCHEMA:media}

spring.docker.compose.file=../docker-compose.yml,../docker-compose.fixedport.yml